FORMAT: 1A
HOST: https://store-manager-api-2.herokuapp.com

# Store manager API

Store Manager is a web application that helps store owners
manage sales and product inventory records.
This application is meant for use in a single store.

ENDPOINTS
**GET /products - Fetch all products Get all available products.**
**GET /products/productId - Fetch a single product record**
**GET /sales - Fetch all sale records Get all sale records.**
**GET /sales/saleId - Fetch a single sale record**
**POST /products - Create a product**
**POST /sales - Create a sale order**
**POST /login - Login user**
**POST /register - Register user**

To begin, remember to add /api/v1 to the heroku link before inserting the endpoints

https://store-manager-api-2.herokuapp.com/api/v1
### Register a user[POST]

You may register a user using the following endpoint

https://store-manager-api-2.herokuapp.com/api/v1/register
+ Request (application/json)
    Sign up/register with username, email and password
        
            {
                "username": "JamesAce",
                "email": "jamesace4@live.com,
                "password": "james200"
                
            }
        

+ Response 201 (application/json)

    + Headers

            Location: api/v1/register

    + Body

            
              {
                 "username": "JamesAce",
                "email": "jamesace4@live.com,
                "password": "james200"
                
            }
         
            
            
### Log in user [POST]
https://store-manager-api-2.herokuapp.com/api/v1/login

+ Response 200 (application/json)

        Log in with your email

+ Request (application/json)

        
            {
                 
                "email": "jamesace4@live.com,
                "password": "james200"
            }
        

+ Response 201 (application/json)

    + Headers

            Location: api/v1/login

    + Body

            
               {
                 
                "email": "jamesace4@live.com,
                "password": "james200"
                }


### Create a Product[POST]

You may post a product

https://store-manager-api-2.herokuapp.com/api/v1/products

+ Request (application/json)

        
            {
                "name": "Shoes",
                "price": 300, 
                "quantity": 3
            }
        

+ Response 201 (application/json)

    + Headers

            Location: api/v1/products

    + Body

            
               {
                "name": "Shoes",
                "price": 300, 
                "quantity": 3
            }
         
            
            
### Get all Products [GET]

https://store-manager-api-2.herokuapp.com/api/v1/products

+ Response 200 (application/json)

        [
            {
                "id": 1
                "name": "Shoes",
                "price": 300,
                "quantity": 3
            },
            {
                "id": 2
                "name": "Clothes",
                "price": 1000,
                "quantity": 3
            }
        ]
        
### Get single product [GET]

 + Headers

            Location: api/v1/products/<productid>
            https://store-manager-api-2.herokuapp.com/api/v1/<productid>
            
+ Response 200 (application/json)

        
            {
                "id": 1
                "name": "Shoes",
                "price": 300,
                "quantity": 3
            }
            
### Create a sale recrod[POST]

You may post a sale record

https://store-manager-api-2.herokuapp.com/api/v1/sales

+ Request (application/json)

        
           {
            
            'description': "Piano black",
            'items': "Playstation"
        }
        

+ Response 201 (application/json)

    + Headers

            Location: api/v1/sales

    + Body

            
               {
            'description': "Piano black",
            'items': "Playstation"
        }
         
            
            
### Get all sales records [GET]
https://store-manager-api-2.herokuapp.com/api/v1/sales

+ Response 200 (application/json)

        [
            {
                "id": 1
                "description": "Piano black",
                "items": "Playstation 4
            },
            {
                "id": 2
                "description": "Piano black",
                "items": "Playstation 4
            }
        ]
        
### Get single sale records [GET]

 + Headers

            Location: api/v1/sales/<salesid>
            https://store-manager-api-2.herokuapp.com/api/v1/sales/<salesid>
            
+ Response 200 (application/json)

        
            {
                "id": 1
                "description": "Piano black",
                "item": "Playstation 4
            }